---

version: 2.1

defaults: &defaults
  working_directory: ~/bestwebua

jobs:
  linters:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Installing linters
          command: |
                curl -1sLf 'https://dl.cloudsmith.io/public/evilmartians/lefthook/setup.deb.sh' | sudo -E bash
                sudo apt-get update -y
                sudo apt-get install -y lefthook yamllint
                npm install --prefix='~/.local' --global --save-dev git+https://github.com/streetsidesoftware/cspell-cli markdownlint-cli
                cp .circleci/linter_configs/.lefthook.yml lefthook.yml
      - run:
          name: Running linters
          command: |
            lefthook run linters

workflows:
  build:
    jobs:
      - linters
