---

no_tty: true
skip_output:
  - meta

linters:
  commands:
    commitspell:
      run: .circleci/scripts/commitspell.sh -c '.circleci/linter_configs/.commitspell.yml'
    cspell:
      run: cspell-cli lint -c '.circleci/linter_configs/.cspell.yml' '**/*.{txt,md}'
    markdownlint:
      run: markdownlint -c '.circleci/linter_configs/.markdownlint.yml' '**/*.md'
    yamllint:
      run: yamllint -c '.circleci/linter_configs/.yamllint.yml' .
